services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: 'verdaccio'
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - '4873:4873'
    volumes:
      - './data/storage:/verdaccio/storage'
      - './data/config:/verdaccio/conf'
      - './data/plugins:/verdaccio/plugins'
networks:
  node-network:
    driver: bridge
